use_frameworks!

PLATFORM_VERSION = '16.0'
SWIFT_VERSION = '5'

platform :ios, '17.0'

target 'SwiftUIGameKit_Example' do
  pod 'SwiftUIGameKit', :path => '../'

  target 'SwiftUIGameKit_Tests' do
    inherit! :search_paths

    
  end
end

# POST INSTALL

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # set the default Swift version for all Pod targets
      config.build_settings['SWIFT_VERSION'] = SWIFT_VERSION
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = PLATFORM_VERSION

      # set testability for all Pod targets
      if config.name.include?('Debug')
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      end

      if target.name.include?('Test')
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      end
    end
  end
end

